###################
# dein.vim
###################
[[plugins]]
repo = 'Shougo/dein.vim'


###################
# Theme
###################
[[plugins]]
repo = 'altercation/vim-colors-solarized'
merged = 0


###################
# Lint
###################
[[plugins]]
repo = 'dense-analysis/ale'
hook_add = '''
let g:ale_disable_lsp = 1
let g:ale_linter_aliases = {
\   'gina-commit': ['markdown'],
\}
let g:ale_fixers = {
\   'javascript': ['prettier-eslint'],
\   'json': ['prettier'],
\   'css': ['prettier'],
\   'scss': ['prettier'],
\   'ruby': ['rubocop'],
\}
nmap <silent> <C-j> <Plug>(ale_next_wrap)
nmap <silent> <C-k> <Plug>(ale_previous_wrap)
'''

###################
# LSP
###################
[[plugins]]
repo = 'prabirshrestha/vim-lsp'
[[plugins]]
repo = 'mattn/vim-lsp-settings'
hook_add = '''
let g:lsp_settings = {
\   'yaml-language-server': {
\       'allowlist': ['yaml', 'yaml.circleci']
\   }
\}
'''
[[plugins]]
repo = 'prabirshrestha/asyncomplete.vim'
[[plugins]]
repo = 'prabirshrestha/asyncomplete-lsp.vim'


###################
# Git
###################
[[plugins]]
repo = 'lambdalisue/gina.vim'
hook_add = '''
    set statusline=%=\ %{gina#component#repo#preset()}[%{(&fenc!=''?&fenc:&enc)}/%{&ff}]\[%Y]\[%04l,%03v][%p%%]
    call gina#custom#mapping#nmap(
            \ 'blame', 'dd',
            \ '<Plug>(gina-changes-of-above)'
            \)
    call gina#custom#mapping#nmap(
            \ 'blame', 'o',
            \ '<Plug>(gina-browse)'
            \)
'''


###################
# Zshef
###################
[[plugins]]
repo = 'yasuhiroki/zshef.vim'

