###################
# dein.vim
###################
[[plugins]]
repo = 'Shougo/dein.vim'


###################
# Theme
###################
[[plugins]]
repo = 'altercation/vim-colors-solarized'
merged = 0


###################
# Lint
###################
[[plugins]]
repo = 'dense-analysis/ale'
hook_add = '''
let g:ale_linter_aliases = {
\   'gina-commit': ['markdown'],
\}
let g:ale_fixers = {
\   'javascript': ['prettier-eslint'],
\   'json': ['prettier'],
\   'css': ['prettier'],
\   'scss': ['prettier'],
\   'ruby': ['rubocop'],
\}
nmap <silent> <C-j> <Plug>(ale_next_wrap)
nmap <silent> <C-k> <Plug>(ale_previous_wrap)

let g:ale_completion_enabled = 1
set omnifunc=ale#completion#OmniFunc
'''


###################
# Git
###################
[[plugins]]
repo = 'lambdalisue/gina.vim'
hook_add = '''
    set statusline=%=\ %{gina#component#repo#preset()}[%{(&fenc!=''?&fenc:&enc)}/%{&ff}]\[%Y]\[%04l,%03v][%p%%]
'''


###################
# Zshef
###################
[[plugins]]
repo = 'yasuhiroki/zshef.vim'

