###################
# dein.vim
###################
[[plugins]]
repo = 'Shougo/dein.vim'


###################
# Theme
###################
[[plugins]]
repo = 'altercation/vim-colors-solarized'
merged = 0


###################
# Lint
###################
[[plugins]]
repo = 'dense-analysis/ale'
hook_add = '''
let g:ale_disable_lsp = 1
let g:ale_virtualtext_cursor = 0
let g:ale_floating_preview = 1
let g:ale_linter_aliases = {
\   'gina-commit': ['markdown'],
\}
let g:ale_linters_explicit = 1
let g:ale_linters = {
\   'python': ['pylint'],
\}
let g:ale_fixers = {
\   'javascript': ['prettier-eslint'],
\   'json': ['prettier'],
\   'css': ['prettier'],
\   'scss': ['prettier'],
\   'ruby': ['rubocop'],
\}

let g:ale_pattern_options = {
\ '\..*\.js$': {'ale_linters': [], 'ale_fixers': []},
\ '\..*\.css$': {'ale_linters': [], 'ale_fixers': []},
\}
let g:ale_pattern_options_enabled = 1

nmap <silent> K <Plug>(ale_detail)
nmap <silent> <C-j> <Plug>(ale_next_wrap)
nmap <silent> <C-k> <Plug>(ale_previous_wrap)
'''

###################
# LSP
###################
[[plugins]]
repo = 'prabirshrestha/vim-lsp'
hook_add = '''
function! s:on_lsp_buffer_enabled() abort
    setlocal omnifunc=lsp#complete
    setlocal signcolumn=yes
    nmap <buffer> gd <plug>(lsp-definition)
    nmap <buffer> gr <plug>(lsp-references)
    nmap <buffer> K <plug>(lsp-hover)
    nmap <buffer> ]c :LspNextDiagnostic<CR>
    nmap <buffer> [c :LspPreviousDiagnostic<CR>
    let g:lsp_format_sync_timeout = 1000
endfunction

augroup lsp_install
    au!
    autocmd User lsp_buffer_enabled call s:on_lsp_buffer_enabled()
augroup END

let g:lsp_diagnostics_echo_cursor = 1
let g:lsp_diagnostics_virtual_text_enabled = 0

" for debugging
" let g:lsp_log_file = './lsp.log'

if !system('bundle exec rubocop -v')
    au User lsp_setup call lsp#register_server({
            \ 'name': 'rubocop',
            \ 'cmd': {server_info->['bundle', 'exec', 'rubocop', '--lsp']},
            \ 'allowlist': ['ruby']
            \ })
else
    au User lsp_setup call lsp#register_server({
            \ 'name': 'rubocop',
            \ 'cmd': {server_info->['rubocop', '--lsp']},
            \ 'allowlist': ['ruby']
            \ })
endif
'''
[[plugins]]
repo = 'mattn/vim-lsp-settings'
hook_add = '''
let g:lsp_settings = {
\   'yaml-language-server': {
\       'allowlist': ['yaml', 'yaml.circleci', 'yaml.gha'],
\       'workspace_config': {
\           'yaml': {
\               'schemas': {
\                   'https://json.schemastore.org/circleciconfig.json': ['.circleci/config.yml'],
\                   'https://json.schemastore.org/github-action.json': ['.github/actions/*.yml']
\               }
\           }
\      }
\   },
\   'typeprof': {'disabled': 1}
\}
'''

[[plugins]]
repo = 'hrsh7th/vim-vsnip'
hook_add = '''
imap <expr> <C-j> vsnip#jumpable(1)   ? '<Plug>(vsnip-jump-next)' : '<C-j>'
smap <expr> <C-j> vsnip#jumpable(1)   ? '<Plug>(vsnip-jump-next)' : '<C-j>'
imap <expr> <C-k> vsnip#jumpable(-1)  ? '<Plug>(vsnip-jump-prev)' : '<C-k>'
smap <expr> <C-k> vsnip#jumpable(-1)  ? '<Plug>(vsnip-jump-prev)' : '<C-k>'

nmap        s   <Plug>(vsnip-select-text)
xmap        s   <Plug>(vsnip-select-text)
nmap        S   <Plug>(vsnip-cut-text)
xmap        S   <Plug>(vsnip-cut-text)

let g:vsnip_filetypes = {}
'''
[[plugins]]
repo = 'hrsh7th/vim-vsnip-integ'
[[plugins]]
repo = 'rafamadriz/friendly-snippets'


###################
# Git
###################
[[plugins]]
repo = 'lambdalisue/gina.vim'
hook_add = '''
    set statusline=%=\ %{gina#component#repo#preset()}[%{(&fenc!=''?&fenc:&enc)}/%{&ff}]\[%Y]\[%04l,%03v][%p%%]
    call gina#custom#mapping#nmap(
            \ 'blame', 'dd',
            \ '<Plug>(gina-changes-of-above)'
            \)
    call gina#custom#mapping#nmap(
            \ 'blame', 'o',
            \ '<Plug>(gina-browse)'
            \)
'''

[[plugins]]
repo = 'vim-denops/denops.vim'
hook_add = '''
    let g:denops_disable_version_check = 1
'''
[[plugins]]
repo = 'lambdalisue/gin.vim'
depends = ['vim-denops/denops.vim']
hook_add = '''
    function! OpenGinTab(ginCommand)
        let searchName = '^' . tolower(a:ginCommand)
        let tabCount = tabpagenr('$')
        for tabnum in range(1, tabCount)
            for winnr in range(1, tabpagewinnr(tabnum, '$'))
                let bufnr = tabpagebuflist(tabnum)[winnr - 1]
                let name = bufname(bufnr)
                if match(name, searchName) != -1
                    execute 'tabn ' . tabnum
                    execute winnr . 'wincmd w'
                    return
                endif
            endfor
        endfor
        execute 'tabnew'
        execute a:ginCommand
    endfunction

	let g:gin_log_default_args = ['--graph', '--decorate']
    autocmd FileType gin-log nnoremap <buffer> <nowait> o <Plug>(gin-action-browse)
    autocmd FileType gin-log nnoremap <buffer> <nowait> f <Plug>(gin-action-fixup)

    nmap <Leader>gs :call OpenGinTab('GinStatus')<CR>
    nmap <Leader>gc :Gin commit<CR>
    nmap <Leader>gl :call OpenGinTab('GinLog')<CR>
    nmap <Leader>gg :Gina qrep 
    nmap <Leader>gb :Gina blame<CR>
'''


###################
# Zshef
###################
[[plugins]]
repo = 'yasuhiroki/zshef.vim'

