[[plugins]]
repo = 'cespare/vim-toml'
on_ft = ['toml']

[[plugins]]
repo = 'Shougo/neosnippet-snippets'
on_i = 1

[[plugins]]
repo = 'Shougo/neosnippet.vim'
depends = ['neosnippet-snippets', 'context_filetype.vim']
on_event = 'InsertCharPre'
on_ft = 'snippet'
hook_source = 'source ~/.vim/dein/neosnippet.rc.vim'

[[plugins]]
repo = 'mattn/emmet-vim'
on_ft = ['html', 'xml']

[[plugins]]
repo = 'hail2u/vim-css3-syntax'
on_ft = ['css', 'scss', 'sass']

[[plugins]]
repo = 'othree/yajs.vim'
on_ft = ['javascrpt', 'typescript']

[[plugins]]
repo = 'jason0x43/vim-js-indent'
on_ft = ['javascrpt', 'typescript', 'html']
hook_source = '''
let g:js_indent_typescript = 1
'''

[[plugins]]
repo = 'othree/html5.vim'
on_ft = ['html']

[[plugins]]
repo = 'marijnh/tern_for_vim'
depends = ['typescript-vim']
build = 'npm install'
on_ft = ['javascript', 'typescript']
hook_source = '''
call tern#Enable()
'''

[[plugins]]
repo = 'Quramy/tsuquyomi'
depends = ['typescript-vim']
on_ft = ['typescript']
hook_source = '''
let g:syntastic_typescript_checkers = ['tsuquyomi']
augroup typescript_key_mapping
  autocmd FileType typescript nmap <buffer> <Leader>e <Plug>(TsuquyomiRenameSymbol)
augroup END
'''

[[plugins]]
repo = 'vim-jp/vim-go-extra'
on_ft = ['go']

