[[plugins]]
repo = 'cespare/vim-toml'
on_ft = ['toml']

[[plugins]]
repo = 'Shougo/neosnippet-snippets'
on_i = 1

[[plugins]]
repo = 'Shougo/neosnippet.vim'
depends = ['neosnippet-snippets', 'context_filetype.vim']
on_event = 'InsertCharPre'
on_ft = 'snippet'
hook_source = 'source ~/.vim/dein/neosnippet.rc.vim'

[[plugins]]
repo = 'Shougo/neocomplete.vim'
depends = 'context_filetype.vim'
if = "has('lua')"
on_event = 'InsertEnter'
hook_source = '''
  let g:neocomplete#enable_at_startup = 1
  source ~/.vim/dein/neocomplete.rc.vim
'''
hook_post_source = '''
  let g:neocomplete#sources#omni#functions.typescript = 'tern#Complete'
  let g:neocomplete#sources#omni#input_patterns.typescript = '[^. \t]\.\%(\h\w*\)\?'
'''

[[plugins]]
repo = 'mattn/emmet-vim'

[[plugins]]
repo = 'hail2u/vim-css3-syntax'
on_ft = ['css', 'scss', 'sass']


[[plugins]]
repo = 'jason0x43/vim-js-indent'
on_ft = ['javascript', 'typescript', 'html']
hook_source = '''
let g:js_indent_typescript = 1
'''

[[plugins]]
repo = 'othree/html5.vim'
on_ft = ['html']

[[plugins]]
repo = 'marijnh/tern_for_vim'
depends = ['typescript-vim']
build = 'npm install'
on_ft = ['javascript', 'typescript']
hook_source = '''
call tern#Enable()
'''

[[plugins]]
repo = 'kana/vim-smartinput'
on_i = 1

[[plugins]]
repo = 'cohama/vim-smartinput-endwise'
on_ft = ['ruby']
hook_source = '''
call smartinput_endwise#define_default_rules()
'''

[[plugins]]
repo = 'Quramy/tsuquyomi'
on_ft = ['typescript']
hook_source = '''
augroup typescript_key_mapping
  autocmd FileType typescript nmap <buffer> <Leader>e <Plug>(TsuquyomiRenameSymbol)
augroup END
'''
