[[plugins]]
repo = 'cespare/vim-toml'
on_ft = ['toml']

[[plugins]]
repo = 'Shougo/neosnippet.vim'
on_i = 1
hook_add = 'let g:neosnippet#enable_snipmate_compatibility = 1'
hook_source = 'imap <C-k> <Plug>(neosnippet_expand_or_jump)'
hook_source = 'smap <C-k> <Plug>(neosnippet_expand_or_jump)'
hook_source = 'xmap <C-k> <Plug>(neosnippet_expand_target)'

[[plugins]]
repo = 'Shougo/neosnippet-snippets'
on_i = 1

[[plugins]]
repo = 'honza/vim-snippets'
on_i = 1
hook_source = 'let g:snips_author = "yasuhiroki"'
hook_source = 'let g:snips_email = "yasuhiroki.duck@gmail.com"'
hook_source = 'let g:snips_github = "https://github.com/yasuhiroki"'

[[plugins]]
repo = 'mattn/emmet-vim'

[[plugins]]
repo = 'hail2u/vim-css3-syntax'
on_ft = ['css', 'scss', 'sass']

[[plugins]]
repo = 'othree/html5.vim'
on_ft = ['html']
