[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'Shougo/neocomplete.vim'
if = "has('lua')"
hook_source = '''
  let g:neocomplete#enable_at_startup = 1
  let g:neocomplete#disable_auto_complete = 0
  let g:neocomplete#enable_smart_case = 1
  let g:neocomplete#enable_camel_case = 1
  let g:neocomplete#auto_complete_delay = 30
  let g:neocomplete#enable_fuzzy_completion = 1
  let g:neocomplete#auto_completion_start_length = 2
  let g:neocomplete#manual_completion_start_length = 0
  let g:neocomplete#min_keyword_length = 3
  if !exists('g:neocomplete#sources#omni#functions')
    let g:neocomplete#sources#omni#functions = {}
  endif
  if !exists('g:neocomplete#sources#omni#input_patterns')
    let g:neocomplete#sources#omni#input_patterns = {}
  endif
  if !exists('g:neocomplete#source#force_omni_input_patterns')
    let g:neocomplete#force_omni_input_patterns = {}
  endif
  if !exists('g:neocomplete#keyword_patterns')
    let g:neocomplete#keyword_patterns = {}
  endif
  let g:neocomplete#sources#omni#functions.typescript = 'tern#Complete'
  let g:neocomplete#sources#omni#input_patterns.typescript = '[^. \t]\.\%(\h\w*\)\?'
  let g:neocomplete#keyword_patterns._ = '\h\k*(\?'

  inoremap <expr> <C-g>     neocomplete#undo_completion()
  inoremap <expr> <C-l>     neocomplete#mappings#complete_common_string()

  " <CR>: close popup and save indent.
  inoremap <silent> <CR> <C-r>=<SID>my_cr_function()<CR>
  function! s:my_cr_function() abort
   return neocomplete#smart_close_popup() . "\<CR>"
  endfunction
'''

[[plugins]]
repo = 'Shougo/neosnippet-snippets'

[[plugins]]
repo = 'Shougo/neosnippet.vim'
depends = ['neosnippet-snippets', 'context_filetype.vim']
hook_source = 'source ~/.vim/dein/neosnippet.rc.vim'

[[plugins]]
repo = 'thinca/vim-quickrun'
hook_add = '''
nnoremap <expr><silent> <C-c> quickrun#is_running() ? quickrun#sweep_sessions() : "\<C-c>"
'''

[[plugins]]
repo = 'tpope/vim-fugitive'
hook_add = '''
    set statusline=%=\ %{fugitive#statusline()}[%{(&fenc!=''?&fenc:&enc)}/%{&ff}]\[%Y]\[%04l,%03v][%p%%]
'''

[[plugins]]
repo = 'cohama/agit.vim'

[[plugins]]
repo = 'idanarye/vim-merginal'

[[plugins]]
repo = 'ctrlpvim/ctrlp.vim'
hook_add = '''
let g:ctrlp_use_migemo = 1 " Don't install migemo yet
let g:ctrlp_clear_cache_on_exit = 0   " Doesn't cache clear when vim quit
let g:ctrlp_mruf_max            = 500 " Max memorable mru
let g:ctrlp_open_new_file       = 1   " Open new file as tab

set wildignore+=*/tmp/*,*.so,*.swp,*.zip     " MacOSX/Linux
set wildignore+=*\\tmp\\*,*.swp,*.zip,*.exe  " Windows

let g:ctrlp_custom_ignore = {
  \ 'dir':  '\v[\/]\.(git|hg|svn)$',
  \ 'file': '\v\.(exe|so|dll)$',
  \ }
'''

[[plugins]]
repo = 'nixprime/cpsm'
build = 'PY3=ON bash install.sh'
depends = ['ctrlp.vim']
hook_add = '''
  let g:ctrlp_match_func = {'match': 'cpsm#CtrlPMatch'}
'''

[[plugins]]
repo = 'rking/ag.vim'
hook_add = '''
if executable('ag')
    let g:ctrlp_use_caching = 0
    let g:ctrlp_user_command = 'ag %s -i --nocolor --nogroup -g ""'
endif
'''

[[plugins]]
repo = 'w0rp/ale'
hook_add = '''
let g:ale_linters = {
\   'javascript': ['eslint'],
\}
nmap <silent> <C-j> <Plug>(ale_next_wrap)
nmap <silent> <C-k> <Plug>(ale_previous_wrap)
'''

[[plugins]]
repo = "aklt/plantuml-syntax"

[[plugins]]
repo = 'Shougo/context_filetype.vim'

[[plugins]]
repo = 'tpope/vim-surround'

[[plugins]]
repo = 'leafgarland/typescript-vim'

[[plugins]]
repo = 'b4b4r07/buftabs'
hook_add = '''
let g:buftabs_only_basename = 1
let g:buftabs_in_statusline = 1
let g:buftabs_active_highlight_group="Visual"
'''

[[plugins]]
repo = 'junegunn/vim-easy-align.git'
hook_add = '''
xmap ga <Plug>(EasyAlign)
nmap ga <Plug>(EasyAlign)
'''

[[plugins]]
repo = 'nathanaelkane/vim-indent-guides'
hook_add = '''
let g:indent_guides_enable_on_vim_startup=1
'''

[[plugins]]
repo = 'scrooloose/nerdtree'

[[plugins]]
repo = 'bronson/vim-trailing-whitespace'

[[plugins]]
repo = 'altercation/vim-colors-solarized'
merged = 0

[[plugins]]
repo = 'LucHermitte/lh-vim-lib'

[[plugins]]
repo = 'LucHermitte/local_vimrc'
depends = ['LucHermitte/lh-vim-lib']

[[plugins]]
repo = 'soramugi/auto-ctags.vim'
hook_add = '''
let g:auto_ctags = 1
let g:auto_ctags_directory_list = ['.git']
let g:auto_ctags_tags_args = '--tag-relative=yes --recurse --sort=yes'
set tags+=.git/tags
'''

[[plugins]]
repo = 'heavenshell/vim-jsdoc'

[[plugins]]
repo = 'rhysd/vim-gfm-syntax'
hook_add = '''
let g:gfm_syntax_emoji_conceal = 1
'''

[[plugins]]
repo = 'thinca/vim-ref'

[[plugins]]
repo = 'ekalinin/Dockerfile.vim'
