###################
# TOML
###################
[[plugins]]
repo = 'cespare/vim-toml'
on_ft = ['toml']


###################
# HTML / CSS
###################
[[plugins]]
repo = 'othree/html5.vim'
on_ft = ['html']

[[plugins]]
repo = 'mattn/emmet-vim'
on_ft = ['html', 'xml', 'markdown']

[[plugins]]
repo = 'hail2u/vim-css3-syntax'
on_ft = ['css', 'scss', 'sass']


###################
# JavaScript / TypeScript
###################
[[plugins]]
repo = 'othree/yajs.vim'
on_ft = ['javascript', 'typescript']

[[plugins]]
repo = 'jason0x43/vim-js-indent'
on_ft = ['javascript', 'typescript', 'html']
hook_source = '''
  let g:js_indent_typescript = 1
'''

[[plugins]]
repo = 'leafgarland/typescript-vim'


###################
# Python
###################
[[plugins]]
on_ft = ['python']
repo = 'Vimjas/vim-python-pep8-indent'


###################
# Go-lang
###################
[[plugins]]
repo = 'mattn/vim-goimports'
on_ft = ['go']

###################
# Elixir
###################
[[plugins]]
repo = 'elixir-lang/vim-elixir'
on_ft = ['elixir']

[[plugins]]
repo = 'slashmili/alchemist.vim'
on_ft = ['elixir']


###################
# PlantUML
###################
[[plugins]]
repo = "aklt/plantuml-syntax"
on_ft = ['plantuml']

[[plugins]]
repo = 'yasuhiroki/vim-plantuml-snippets'
on_ft = ['plantuml']

[[plugins]]
repo = 'yasuhiroki/vim-aws-plantuml-snippets'
depends = ['vim-plantuml-snippets']
on_ft = ['plantuml']
